### ISSUE TITLE
Error al Descargar rasters en islas de calor

### ISSUE THREAD

**Issue by sorianocom** [EL-BID/URSA#12]
Hola. 
Encontramos un error al presionar el botón de Descargar Rasters en la app cuando seleccionamos la capa de Islas de Calor.
Seleccionamos el cuadrante de Uruguay - Montevideo (No probamos si esto mismo sucede en otro cuadrante)
Al presionar el botón de "Descargar rasters"  el mensaje en el log es el siguiente:

172.17.0.1 - - [09/Mar/2024 13:29:09] "POST /_dash-update-component HTTP/1.1" 200 -
172.17.0.1 - - [09/Mar/2024 13:29:09] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
Generating temperature discrete image ...
Done.
Generating temperature map ...
172.17.0.1 - - [09/Mar/2024 13:29:12] "POST /_dash-update-component HTTP/1.1" 200 -
Done.
172.17.0.1 - - [09/Mar/2024 13:29:19] "POST /_dash-update-component HTTP/1.1" 200 -
[2024-03-09 13:29:32,042] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/app/pages/suhi.py", line 831, in start_download
    img_cat = ht.get_cat_suhi_raw(lst, masks, path_cache)
AttributeError: module 'ursa.heat_islands' has no attribute 'get_cat_suhi_raw'. Did you mean: 'get_cat_suhi'?
172.17.0.1 - - [09/Mar/2024 13:29:32] "POST /_dash-update-component HTTP/1.1" 500 -

Muchas gracias por la ayuda.

**Comment by ricardorobles** [comment]
Tengo el mismo problema para el caso de Rosario - Argentina.

**Comment by bitsandbricks** [comment]
@sorianocom , @ricardorobles gracias por el aviso.
El problema esta resuelto - pueden descargar el código actualizado e intentar otra vez

**Comment by sorianocom** [comment]
Quedó resuleto, probamos y funcionaron las descargas. Muchas gracias @bitsandbricks
