### ISSUE TITLE
Error al autenticar

### ISSUE THREAD

**Issue by cslamo** [EL-BID/URSA#6]
Buenas. Sigo las instrucciones para la instalacion en windows. Todo bien hasta que me pide el codigo de autenticacion. Al ingresarlo me tira siguiente error. Algun consejo? Gracias!

Traceback (most recent call last):
  File "/opt/conda/envs/ursa/bin/earthengine", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/cli/eecli.py", line 87, in main
    _run_command()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/cli/eecli.py", line 61, in _run_command
    dispatcher.run(args, config)
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/cli/commands.py", line 361, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/cli/commands.py", line 406, in run
    ee.Authenticate(**args_auth)
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/__init__.py", line 105, in Authenticate
    oauth.authenticate(
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 430, in authenticate
    flow.save_code()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 479, in save_code
    _obtain_and_write_token(code, self.code_verifier, self.scopes, redirect_uri)
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 197, in _obtain_and_write_token
    client_info = {k: fetched_info[k] for k in ['client_id', 'client_secret']}
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 197, in <dictcomp>
    client_info = {k: fetched_info[k] for k in ['client_id', 'client_secret']}
KeyError: 'client_id'
Traceback (most recent call last):
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/data.py", line 236, in get_persistent_credentials
    None, **oauth.get_credentials_arguments()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 72, in get_credentials_arguments
    with open(get_credentials_path()) as creds:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/earthengine/credentials'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 86, in <module>
    ee.Initialize()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/__init__.py", line 134, in Initialize
    credentials = data.get_persistent_credentials()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/data.py", line 239, in get_persistent_credentials
    raise ee_exception.EEException(  # pylint: disable=raise-missing-from
ee.ee_exception.EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/data.py", line 236, in get_persistent_credentials
    None, **oauth.get_credentials_arguments()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/oauth.py", line 72, in get_credentials_arguments
    with open(get_credentials_path()) as creds:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/earthengine/credentials'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 91, in <module>
    ee.Initialize()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/__init__.py", line 134, in Initialize
    credentials = data.get_persistent_credentials()
  File "/opt/conda/envs/ursa/lib/python3.10/site-packages/ee/data.py", line 239, in get_persistent_credentials
    raise ee_exception.EEException(  # pylint: disable=raise-missing-from
ee.ee_exception.EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.
ERROR conda.cli.main_run:execute(47): `conda run python -u app.py` failed. (See above for error)

**Comment by Pampsp** [comment]
¡Buenas noches!
me pasa el mismo error de arriba. He reinstalado python y anaconda, pero el error persiste. ¿Alguien me puede ayudar?

**Comment by Pampsp** [comment]
> Boas noites! me passa o mesmo erro de arriba. Ele reinstalou python e anaconda, mas o erro persistiu. Você pode me ajudar?

**Comment by Pampsp** [comment]
deu certo! ;)

**Comment by bitsandbricks** [comment]
Hola! Ola!

I was able to reproduce the error. We are looking into it, and hope to have a fix soon.

Obrigado/Gracias por reportar!

**Comment by bitsandbricks** [comment]
@cslamo @Pampsp please download the latest version and try again.

Or just edit "launcher.bat" and change it from

`docker run -i -v bidcache:/app/data/cache -p 8050:8050 bid-urban-growth`

to

`docker run -it -v bidcache:/app/data/cache -p 8050:8050 bid-urban-growth`

notice that the only change is the "t" flag: -i**t**  instead of just -i

That ensures that the container opens an interactive terminal, so you get the message asking to authenticate on Google Earth Engine and can provide the token and go on using the app.

Let me know if it works for you!

**Comment by Pampsp** [comment]
eu não to conseguindo baixar o raster parar meu google drive na opção ilhas de calor.

  File "/app/pages/suhi.py", line 596, in start_download
    task = ht.download_cat_suhi(bbox_latlon, path_cache, "Qall", 2022)
  File "/app/src/ursa/heat_islands.py", line 143, in download_cat_suhi
    img_cat = get_cat_suhi(bbox_ee, start_date, end_date, path_cache)
TypeError: get_cat_suhi() missing 1 required positional argument: 'path_cache'
172.17.0.1 - - [17/Dec/2023 16:20:31] "POST /_dash-update-component HTTP/1.1" 500

**Comment by diablourbano** [comment]
I solved it opening ./app.py and adding `ee.Authenticate()` below `ee.Initialize()`

**Comment by bitsandbricks** [comment]
Hi @Pampsp  , does the solution suggested by @diablourbano work for you?
